# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'connect4.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys


def main():
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(469, 347)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 30, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.difficultlyBox = QtWidgets.QGroupBox(self.centralwidget)
        self.difficultlyBox.setGeometry(QtCore.QRect(50, 100, 120, 141))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.difficultlyBox.setFont(font)
        self.difficultlyBox.setObjectName("difficultlyBox")
        self.difficultlyBox.setFlat(True)
        self.easyRadio = QtWidgets.QRadioButton(self.difficultlyBox)
        self.easyRadio.setGeometry(QtCore.QRect(10, 40, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.easyRadio.setFont(font)
        self.easyRadio.setObjectName("easyRadio")
        self.easyRadio.setChecked(True)
        self.mediumRadio = QtWidgets.QRadioButton(self.difficultlyBox)
        self.mediumRadio.setGeometry(QtCore.QRect(10, 70, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mediumRadio.setFont(font)
        self.mediumRadio.setObjectName("mediumRadio")
        self.hardRadio = QtWidgets.QRadioButton(self.difficultlyBox)
        self.hardRadio.setGeometry(QtCore.QRect(10, 100, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.hardRadio.setFont(font)
        self.hardRadio.setObjectName("hardRadio")
        self.algorithmBox = QtWidgets.QGroupBox(self.centralwidget)
        self.algorithmBox.setGeometry(QtCore.QRect(200, 100, 191, 111))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.algorithmBox.setFont(font)
        self.algorithmBox.setObjectName("algorithmBox")
        self.algorithmBox.setFlat(True)
        self.minmaxRadio = QtWidgets.QRadioButton(self.algorithmBox)
        self.minmaxRadio.setGeometry(QtCore.QRect(10, 40, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.minmaxRadio.setFont(font)
        self.minmaxRadio.setObjectName("minmaxRadio")
        self.minmaxRadio.setChecked(True)
        self.alphabetaRadio = QtWidgets.QRadioButton(self.algorithmBox)
        self.alphabetaRadio.setGeometry(QtCore.QRect(10, 70, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.alphabetaRadio.setFont(font)
        self.alphabetaRadio.setObjectName("alphabetaRadio")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(190, 280, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.startButton.setFont(font)
        self.startButton.setObjectName("startButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Welcome to Connect Four!"))
        self.difficultlyBox.setTitle(_translate("MainWindow", "Difficultly"))
        self.easyRadio.setText(_translate("MainWindow", "Easy"))
        self.mediumRadio.setText(_translate("MainWindow", "Medium"))
        self.hardRadio.setText(_translate("MainWindow", "Hard"))
        self.algorithmBox.setTitle(_translate("MainWindow", "Algorithm"))
        self.minmaxRadio.setText(_translate("MainWindow", "Min-Max Algorithm"))
        self.alphabetaRadio.setText(_translate("MainWindow", "Alpha-Beta Pruning Algorithm"))
        self.startButton.setText(_translate("MainWindow", "Start"))

if __name__ == "__main__":
   main()